@startuml
title ユースケース：アプリを起動する
actor user
participant Android
participant presentation
participant model

activate user
user -> Android : アプリのアイコン押下
activate Android
Android -> presentation : アプリ起動
deactivate Android
activate presentation
presentation -> user : モード選択画面表示
deactivate presentation
@enduml

@startuml
title ユースケース：子モードを選択する
actor user
participant presentation
participant model

activate user
user -> presentation : 「子モード」ボタン押下
activate presentation
presentation -> user : 俳句入力画面表示
deactivate presentation
@enduml

@startuml
title ユースケース：俳句を投句する
actor user
participant presentation
participant model

activate user
user -> presentation : 俳句、作者名を入力
activate presentation
user -> presentation : 「投句する」ボタン押下
return QRコード表示
@enduml

@startuml
title ユースケース：親モードを選択する
actor user
participant presentation
participant model

activate user
user -> presentation : 「親モード」ボタン押下
activate presentation
presentation -> model : BGM再生
activate model
presentation -->user : 句会設定画面表示
deactivate presentation
@enduml

@startuml
title ユースケース：句会を開始する
actor user
participant presentation
participant model

activate user
user -> presentation : 句会名・開始日・終了日入力
activate presentation
user -> presentation : 「句会を開始する」ボタン押下
presentation -> model : 句会情報作成
activate model
return 作成成功or失敗
deactivate model
presentation --> user : 俳句読み取り画面表示
deactivate presentation
@enduml

@startuml
title ユースケース：俳句読み取り画面を表示する
actor user
participant presentation
participant model

activate user
user -> presentation : 「句会を開始する」ボタン押下
activate presentation
return 俳句読み取り画面表示
@enduml

@startuml
title ユースケース：俳句を読み取る
actor user
participant presentation
participant model

activate user
user -> presentation : 「俳句を読み取る」ボタン押下
activate presentation
user -> presentation : QRコード読み取り
presentation -> model : 俳句登録
activate model
return 登録成功or失敗
return 読み取り成功or失敗
@enduml

@startuml
title ユースケース：俳句一覧画面を表示する
actor user
participant presentation
participant model

activate user
user -> presentation : 「読み取り完了」ボタン押下
activate presentation
presentation -> model : 俳句シャッフル
activate model
return シャッフル済み俳句リスト
return シャッフル済み俳句一覧画面表示
@enduml

@startuml
title ユースケース：俳句を加点する
actor user
participant presentation
participant model

activate user
user -> presentation : 加点ボタン押下
activate presentation
presentation -> model : 俳句をランダムに加点
activate model
return
return エフェクト表示
@enduml

@startuml
title ユースケース：俳句を減点する
actor user
participant presentation
participant model

activate user
user -> presentation : 減点ボタン押下
activate presentation
presentation -> model : 俳句をランダムに減点
activate model
return
return エフェクト・減点時画像表示
@enduml

@startuml
title ユースケース：句会の結果を表示する
actor user
participant presentation
participant model

activate user
user -> presentation : 「結果を表示する」ボタン押下
activate presentation
presentation -> model : 点数順に俳句をソート
activate model
return ソート済俳句・作者リスト
return 結果画面（点数順の俳句・作者リスト）表示
@enduml